#!/bin/bash
# =============================================================
# Script: sysreport.sh
# Description: Generates a system information report including
#              hardware details, network configuration, and
#              current system status. Designed to provide a
#              quick overview without running multiple commands.
# Author: Harikrishnan PB
# =============================================================

# lshw: lists hardware details; -class filters by category
# ip r: shows routing table; used to find default gateway
# ss -tuln: shows listening TCP/UDP ports without resolving names
# free -h: shows RAM in human-readable format
# /proc/loadavg: kernel file containing live load average values
# ufw: uncomplicated firewall; status shows if it's active

# --- System Identity ---
HOSTNAME=$(hostname)
USERNAME=$(whoami)
DATETIME=$(date "+%Y-%m-%d %H:%M:%S")
OS=$(source /etc/os-release && echo "$PRETTY_NAME")
UPTIME=$(uptime -p)
CPU=$(lshw -class processor 2>/dev/null | grep "product" | head -1 | awk -F: '{print $2}' | xargs)
RAM=$(free -h | awk '/^Mem:/ {print $2}')
DISKS=$(sudo lshw -class disk 2>/dev/null | grep -E "product:|size:" | grep -v "configuration" | awk -F': ' '/product/{p=$2} /size/ && /GiB/{print p, $2; p=""}' | tr '\n' ' ')
VIDEO=$(lshw -class display 2>/dev/null | grep "product" | head -1 | awk -F: '{print $2}' | xargs)

# --- Network ---
GW_IFACE=$(ip r | awk '/default/ {print $5}' | head -1)
HOST_IP=$(ip a show "$GW_IFACE" 2>/dev/null | awk '/inet / {print $2}' | cut -d/ -f1 | head -1)
GATEWAY=$(ip r | awk '/default/ {print $3}' | head -1)
DNS=$(grep "^nameserver" /etc/resolv.conf | awk '{print $2}' | head -1)

# --- System Status ---
USERS=$(who | awk '{print $1}' | sort -u | paste -sd, -)
DISKSPACE=$(df -h --output=target,avail -x tmpfs -x devtmpfs | tail -n +2 | awk '{printf "%s %s  ", $1, $2}')
PROCS=$(ps aux | tail -n +2 | wc -l)
LOADAVG=$(cat /proc/loadavg | awk '{print $1", "$2", "$3}')
PORTS=$(ss -tuln | awk 'NR>1 && /LISTEN/ {print $5}' | awk -F: '{print $NF}' | sort -un | paste -sd, -)
UFW=$(sudo ufw status 2>/dev/null | head -1 | awk '{print $2}')

# --- Output Report ---
cat <<EOF

====================================================
  System Report for $HOSTNAME
  Generated by: $USERNAME
  Date/Time:    $DATETIME
====================================================

  SYSTEM INFORMATION
  ------------------
  OS:           $OS
  Uptime:       $UPTIME
  CPU:          $CPU
  RAM:          $RAM
  Disk(s):      $DISKS
  Video:        $VIDEO
  Host Address: $HOST_IP
  Gateway IP:   $GATEWAY
  DNS Server:   $DNS

  SYSTEM STATUS
  -------------
  Users Logged In:        $USERS
  Disk Space:             $DISKSPACE
  Process Count:          $PROCS
  Load Averages:          $LOADAVG
  Listening Ports:        $PORTS
  UFW Status:             $UFW

====================================================

EOF
